"""
Multi-language support for the Image Processing Application
"""

TRANSLATIONS = {
    'en': {
        # Main app
        'app_title': 'Digital Image Processing Application',
        'app_description': 'A comprehensive tool for digital image processing with real-time preview',
        'sidebar_title': 'Image & Filters',
        'upload_image': 'Upload Image',
        'upload_help': 'Supported formats: PNG, JPG, JPEG, BMP, TIFF',
        'image_info': 'Image Information',
        'filter_categories': 'Filter Categories',
        'select_category': 'Select Category',
        'original_image': 'Original Image',
        'processed_image': 'Processed Image',
        'download_image': 'Download Processed Image',
        'welcome_message': 'Welcome! Upload an image to start processing',
        'sample_images': 'Sample Images',
        'select_sample': 'Select a sample image',
        'load_sample': 'Load Sample',
        'footer': 'Built with Streamlit • Advanced Image Processing Techniques',
        
        # Categories
        'fundamentals': 'Fundamentals',
        'transforms': 'Intensity Transforms',
        'frequency': 'Frequency Domain',
        'restoration': 'Image Restoration',
        'color': 'Color Processing',
        'wavelets': 'Wavelet Transform',
        'compression': 'Image Compression',
        'morphological': 'Morphological Operations',
        'segmentation': 'Image Segmentation',
        'features': 'Feature Extraction',
        
        # Filter names
        'gaussian_blur': 'Gaussian Blur',
        'edge_detection': 'Edge Detection',
        'threshold': 'Thresholding',
        'intensity_transform': 'Intensity Transform',
        'frequency_filter': 'Frequency Filter',
        'noise_reduction': 'Noise Reduction',
        'add_noise': 'Add Noise',
        'pseudocolor': 'Pseudocolor',
        'color_balance': 'Color Balance',
        'color_smoothing': 'Color Smoothing',
        'color_space': 'Color Space Conversion',
        'wavelet_transform': 'Wavelet Transform',
        'compression_filter': 'Compression',
        'morphological_op': 'Morphological Operation',
        'segmentation_filter': 'Segmentation',
        'feature_extraction': 'Feature Extraction',
        
        # Parameters
        'kernel_size': 'Kernel Size',
        'sigma': 'Sigma (σ)',
        'method': 'Method',
        'threshold_value': 'Threshold Value',
        'max_value': 'Maximum Value',
        'alpha': 'Alpha',
        'beta': 'Beta',
        'gamma': 'Gamma',
        'cutoff': 'Cutoff Frequency',
        'intensity': 'Intensity',
        'quality': 'Quality',
        'iterations': 'Iterations',
        'kernel_shape': 'Kernel Shape',
        'r_scale': 'Red Scale',
        'g_scale': 'Green Scale',
        'b_scale': 'Blue Scale',
        'target_space': 'Target Color Space',
        'wavelet_type': 'Wavelet Type',
        'level': 'Decomposition Level',
        'operation': 'Operation',
        'noise_type': 'Noise Type',
        'filter_type': 'Filter Type',
        'transform_type': 'Transform Type',
        'compression_type': 'Compression Type',
        'feature_type': 'Feature Type',
        'k_clusters': 'Number of Clusters',
        
        # Buttons
        'apply_filter': 'Apply Filter',
        'reset_image': 'Reset Image',
        'show_info': 'Show Information',
        
        # Method options
        'sobel': 'Sobel',
        'canny': 'Canny',
        'binary': 'Binary',
        'otsu': 'Otsu',
        'adaptive': 'Adaptive',
        'linear': 'Linear',
        'logarithmic': 'Logarithmic',
        'power_law': 'Power Law',
        'histogram_eq': 'Histogram Equalization',
        'lowpass': 'Low Pass',
        'highpass': 'High Pass',
        'bandpass': 'Band Pass',
        'gaussian': 'Gaussian',
        'salt_pepper': 'Salt & Pepper',
        'speckle': 'Speckle',
        'median': 'Median',
        'bilateral': 'Bilateral',
        'erosion': 'Erosion',
        'dilation': 'Dilation',
        'opening': 'Opening',
        'closing': 'Closing',
        'rect': 'Rectangle',
        'ellipse': 'Ellipse',
        'cross': 'Cross',
        'watershed': 'Watershed',
        'grabcut': 'GrabCut',
        'kmeans': 'K-Means',
        'basic': 'Basic Features',
        'texture': 'Texture Features',
        'color_hist': 'Color Histogram',
        'haar': 'Haar',
        'db4': 'Daubechies 4',
        'bior2.2': 'Biorthogonal 2.2',
        'jpeg': 'JPEG',
        'wavelet': 'Wavelet',
        'rle': 'Run Length Encoding',
        'huffman': 'Huffman Coding',
        'rgb': 'RGB',
        'hsv': 'HSV',
        'lab': 'LAB',
        'yuv': 'YUV',
        'gray': 'Grayscale',
        
        # UI Elements
        'title': '📷 Image Processing Application',
        'upload_header': '📁 Upload Image',
        'upload_text': 'Select an image',
        'upload_info': '👈 Please upload an image from the left to get started.',
        'filter_selection': '🔧 Filter Selection',
        'category_select': 'Select Category',
        'filter_select': 'Select Filter',
        'result': '📊 Result',
        'download': '💾 Download',
        'download_button': 'Download Processed Image',
        'uploaded_image': '📷 Uploaded Image',
        'filter_settings': '🔧 Filter Settings',
        'tip': '💡 Tip',
        'light_blur': 'Light',
        'medium_blur': 'Medium',
        'strong_blur': 'Strong',
        'sensitive_detection': 'Sensitive',
        'medium_detection': 'Medium',
        'selective_detection': 'Selective',
        'fixed_threshold': 'Fixed thresholding',
        'auto_threshold': 'Automatic threshold calculation',
        'local_threshold': 'Local thresholding',
        'brightens': 'Brightens',
        'no_change': 'No change',
        'darkens': 'Darkens',
        'illuminates_dark': 'Illuminates dark areas',
        'simple_contrast': 'Simple contrast adjustment',
        'smoothing_noise': 'Smoothing and noise reduction',
        'sharpening_detail': 'Sharpening and detail enhancement',
        'selective_filtering': 'Selective frequency filtering',
        'neighborhood_diameter': 'Neighborhood Diameter',
        'color_sigma': 'Color Sigma',
        'space_sigma': 'Space Sigma',
        'bilateral_tip': 'Bilateral filter provides the highest quality noise reduction while preserving edges',
        'salt_pepper_ideal': 'Ideal for salt-pepper noise',
        'general_noise': 'General noise reduction',
        'noise_cleaning': 'Noise cleaning and object separation',
        'gap_filling': 'Gap filling and object merging',
        'object_shrinking': 'Object shrinking and erosion',
        'object_expansion': 'Object expansion and dilation',
        'watershed_tip': 'Watershed segmentation is very effective in separating overlapping objects',
        'simple_segmentation': 'Simple segmentation',
        'detailed_segmentation': 'Detailed segmentation',
        'very_detailed_segmentation': 'Very detailed segmentation',
        'sobel_tip': 'Sobel operator provides fast and effective edge detection',
        'about_app': '🎯 About This Application',
        'image_load_error': 'Image could not be loaded!',
        'file_not_found': 'Information file not found',
        'file_read_error': 'File reading error',
        'basic_filters': 'Basic Filters',
        'advanced_filters': 'Advanced Filters',
        'morphological_operations': 'Morphological Operations',
        'segmentation_filters': 'Segmentation',
        'lower_threshold': 'Lower Threshold',
        'upper_threshold': 'Upper Threshold',
        'clusters': 'Clusters',
    },
    
    'tr': {
        # Main app
        'app_title': 'Dijital Görüntü İşleme Uygulaması',
        'app_description': 'Gerçek zamanlı önizleme ile kapsamlı dijital görüntü işleme aracı',
        'sidebar_title': 'Görüntü & Filtreler',
        'upload_image': 'Görüntü Yükle',
        'upload_help': 'Desteklenen formatlar: PNG, JPG, JPEG, BMP, TIFF',
        'image_info': 'Görüntü Bilgisi',
        'filter_categories': 'Filtre Kategorileri',
        'select_category': 'Kategori Seç',
        'original_image': 'Orijinal Görüntü',
        'processed_image': 'İşlenmiş Görüntü',
        'download_image': 'İşlenmiş Görüntüyü İndir',
        'welcome_message': 'Hoş geldiniz! İşleme başlamak için bir görüntü yükleyin',
        'sample_images': 'Örnek Görüntüler',
        'select_sample': 'Örnek görüntü seçin',
        'load_sample': 'Örneği Yükle',
        'footer': 'Streamlit ile Geliştirildi • Gelişmiş Görüntü İşleme Teknikleri',
        
        # Categories
        'fundamentals': 'Temel Kavramlar',
        'transforms': 'Yoğunluk Dönüşümleri',
        'frequency': 'Frekans Alanı',
        'restoration': 'Görüntü Restorasyon',
        'color': 'Renk İşleme',
        'wavelets': 'Wavelet Dönüşümü',
        'compression': 'Görüntü Sıkıştırma',
        'morphological': 'Morfolojik İşlemler',
        'segmentation': 'Görüntü Bölütleme',
        'features': 'Özellik Çıkarımı',
        
        # Filter names
        'gaussian_blur': 'Gaussian Bulanıklaştırma',
        'edge_detection': 'Kenar Belirleme',
        'threshold': 'Eşikleme',
        'intensity_transform': 'Yoğunluk Dönüşümü',
        'frequency_filter': 'Frekans Filtresi',
        'noise_reduction': 'Gürültü Azaltma',
        'add_noise': 'Gürültü Ekleme',
        'pseudocolor': 'Sahte Renk',
        'color_balance': 'Renk Dengesi',
        'color_smoothing': 'Renk Yumuşatma',
        'color_space': 'Renk Uzayı Dönüşümü',
        'wavelet_transform': 'Wavelet Dönüşümü',
        'compression_filter': 'Sıkıştırma',
        'morphological_op': 'Morfolojik İşlem',
        'segmentation_filter': 'Bölütleme',
        'feature_extraction': 'Özellik Çıkarımı',
        
        # Parameters
        'kernel_size': 'Çekirdek Boyutu',
        'sigma': 'Sigma (σ)',
        'method': 'Yöntem',
        'threshold_value': 'Eşik Değeri',
        'max_value': 'Maksimum Değer',
        'alpha': 'Alpha',
        'beta': 'Beta',
        'gamma': 'Gamma',
        'cutoff': 'Kesim Frekansı',
        'intensity': 'Yoğunluk',
        'quality': 'Kalite',
        'iterations': 'Tekrarlama',
        'kernel_shape': 'Çekirdek Şekli',
        'r_scale': 'Kırmızı Ölçek',
        'g_scale': 'Yeşil Ölçek',
        'b_scale': 'Mavi Ölçek',
        'target_space': 'Hedef Renk Uzayı',
        'wavelet_type': 'Wavelet Türü',
        'level': 'Ayrıştırma Seviyesi',
        'operation': 'İşlem',
        'noise_type': 'Gürültü Türü',
        'filter_type': 'Filtre Türü',
        'transform_type': 'Dönüşüm Türü',
        'compression_type': 'Sıkıştırma Türü',
        'feature_type': 'Özellik Türü',
        'k_clusters': 'Küme Sayısı',
        
        # Buttons
        'apply_filter': 'Filtreyi Uygula',
        'reset_image': 'Görüntüyü Sıfırla',
        'show_info': 'Bilgi Göster',
        
        # Method options
        'sobel': 'Sobel',
        'canny': 'Canny',
        'binary': 'İkili',
        'otsu': 'Otsu',
        'adaptive': 'Uyarlanabilir',
        'linear': 'Doğrusal',
        'logarithmic': 'Logaritmik',
        'power_law': 'Güç Yasası',
        'histogram_eq': 'Histogram Eşitleme',
        'lowpass': 'Alçak Geçiren',
        'highpass': 'Yüksek Geçiren',
        'bandpass': 'Bant Geçiren',
        'gaussian': 'Gaussian',
        'salt_pepper': 'Tuz & Biber',
        'speckle': 'Benek',
        'median': 'Medyan',
        'bilateral': 'Bilateral',
        'erosion': 'Aşındırma',
        'dilation': 'Genişletme',
        'opening': 'Açma',
        'closing': 'Kapama',
        'rect': 'Dikdörtgen',
        'ellipse': 'Elips',
        'cross': 'Çapraz',
        'watershed': 'Watershed',
        'grabcut': 'GrabCut',
        'kmeans': 'K-Ortalama',
        'basic': 'Temel Özellikler',
        'texture': 'Doku Özellikleri',
        'color_hist': 'Renk Histogramı',
        'haar': 'Haar',
        'db4': 'Daubechies 4',
        'bior2.2': 'Biorthogonal 2.2',
        'jpeg': 'JPEG',
        'wavelet': 'Wavelet',
        'rle': 'Uzunluk Kodlama',
        'huffman': 'Huffman Kodlama',
        'rgb': 'RGB',
        'hsv': 'HSV',
        'lab': 'LAB',
        'yuv': 'YUV',
        'gray': 'Gri Tonlama',
        
        # UI Elements
        'title': '📷 Görüntü İşleme Uygulaması',
        'upload_header': '📁 Görüntü Yükle',
        'upload_text': 'Bir görüntü seçin',
        'upload_info': '👈 Başlamak için lütfen sol taraftan bir görüntü yükleyin.',
        'filter_selection': '🔧 Filtre Seçimi',
        'category_select': 'Kategori Seçin',
        'filter_select': 'Filtre Seçin',
        'result': '📊 Sonuç',
        'download': '💾 İndir',
        'download_button': 'İşlenmiş Görüntüyü İndir',
        'uploaded_image': '📷 Yüklenen Görüntü',
        'filter_settings': '🔧 Filtre Ayarları',
        'tip': '💡 İpucu',
        'light_blur': 'Hafif',
        'medium_blur': 'Orta',
        'strong_blur': 'Güçlü',
        'sensitive_detection': 'Hassas',
        'medium_detection': 'Orta',
        'selective_detection': 'Seçici',
        'fixed_threshold': 'Sabit eşikleme',
        'auto_threshold': 'Otomatik eşik hesaplama',
        'local_threshold': 'Yerel eşikleme',
        'brightens': 'Aydınlatır',
        'no_change': 'Değişiklik yok',
        'darkens': 'Koyulaştırır',
        'illuminates_dark': 'Karanlık alanları aydınlatır',
        'simple_contrast': 'Basit kontrast ayarı',
        'smoothing_noise': 'Yumuşatma ve gürültü azaltma',
        'sharpening_detail': 'Keskinleştirme ve detay artırma',
        'selective_filtering': 'Seçici frekans filtreleme',
        'neighborhood_diameter': 'Komşuluk Çapı',
        'color_sigma': 'Renk Sigma',
        'space_sigma': 'Uzay Sigma',
        'bilateral_tip': 'Bilateral filtre kenarları koruyarak en kaliteli gürültü azaltmayı sağlar',
        'salt_pepper_ideal': 'Tuz-biber gürültüsü için ideal',
        'general_noise': 'Genel gürültü azaltma',
        'noise_cleaning': 'Gürültü temizleme ve nesne ayırma',
        'gap_filling': 'Boşluk doldurma ve nesne birleştirme',
        'object_shrinking': 'Nesne küçültme ve aşındırma',
        'object_expansion': 'Nesne büyütme ve genişletme',
        'watershed_tip': 'Watershed segmentasyonu çakışan nesneleri ayırmada çok etkilidir',
        'simple_segmentation': 'Basit segmentasyon',
        'detailed_segmentation': 'Detaylı segmentasyon',
        'very_detailed_segmentation': 'Çok detaylı segmentasyon',
        'sobel_tip': 'Sobel operatörü hızlı ve etkili kenar tespiti yapar',
        'about_app': '🎯 Bu Uygulama Hakkında',
        'image_load_error': 'Görüntü yüklenemedi!',
        'file_not_found': 'Bilgi dosyası bulunamadı',
        'file_read_error': 'Dosya okuma hatası',
        'basic_filters': 'Temel Filtreler',
        'advanced_filters': 'Gelişmiş Filtreler',
        'morphological_operations': 'Morfolojik İşlemler',
        'segmentation_filters': 'Segmentasyon',
        'lower_threshold': 'Alt Eşik',
        'upper_threshold': 'Üst Eşik',
        'clusters': 'Kümeler',
    }
}

def get_translations(language='en'):
    """Get translations for specified language"""
    return TRANSLATIONS.get(language, TRANSLATIONS['en'])

def get_text(key, language='en'):
    """Get specific text for a key in the specified language"""
    translations = get_translations(language)
    return translations.get(key, key) 